DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS verses;
DROP TABLE IF EXISTS punctuation;

CREATE TABLE punctuation
(
    id INTEGER NOT NULL PRIMARY KEY,
    tokenIdAfter INTEGER NOT NULL,
    tokenIdBefore INTEGER NOT NULL,
    value VARCHAR(255) NOT NULL
);